### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by iabeefe** [ZG089/Re-Malwack#15]
Mind using Hagezi Ultimate Hostlist(https://github.com/hagezi/dns-blocklists). It blocks more than the list you're currently using.

**Comment by ZG089** [comment]
> Mind using Hagezi Ultimate Hostlist(https://github.com/hagezi/dns-blocklists). It blocks more than the list you're currently using.

@iabeefe its already [used](https://github.com/ZG089/Re-Malwack/blob/3b180579454c2d8af061563730b2cc226a9ecf7f/system/bin/rmlwk#L121), I used Hagezi's Ultimate hostlist (Compressed), and it doesn't block much ads -even my device became very laggy after using it- I plan to change it anyways and use other sources' hostlist.

**Comment by ZG089** [comment]
Issue closed due to inactivity.
